version: "3.3"

services:
  api:
    build: "."
    restart: "always"
    networks:
      - "api.network"
    ports:
      - 5000

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "8080:8080"
    networks:
      - "api.network"

networks:
  api.network:
